run:
  fast: true
  timeout: 5m

linters:
  disable-all: true
  enable:
  - gofmt
  - goimports
  - revive
  - staticcheck
  - gocyclo
  - ineffassign
  - misspell
  - gocritic
  - govet
  - unconvert
  - gosec
