before:
  hooks:
    - go mod download
builds:
  - flags:
      - -buildmode=exe
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./main.go
    ldflags:
     - -s -w -X github.com/bringg/honey/cmd.version={{.Version}} -X github.com/bringg/honey/cmd.commit={{.Commit}} -X github.com/bringg/honey/cmd.date={{.Date}} -X github.com/bringg/honey/cmd.builtBy=goreleaser
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
archives:
  -
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
  -
    id: homebrew
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
- tap:
    owner: bringg
    name: homebrew-honey
  folder: Formula
  url_template: "https://github.com/bringg/honey/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://github.com/bringg/honey"
  description: "DevOps tool to help find an instance in sea of clouds."
  # IDs of the archives to use.
    # Defaults to all.
  ids:
  - foo
  - bar
  - shmar