// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package place

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComShareed2kHoneyPkgPlace(in *jlexer.Lexer, out *Printable) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Printable, 0, 8)
			} else {
				*out = Printable{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *Instance
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(Instance)
				}
				easyjson6601e8cdDecodeGithubComShareed2kHoneyPkgPlace1(in, v1)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComShareed2kHoneyPkgPlace(out *jwriter.Writer, in Printable) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				easyjson6601e8cdEncodeGithubComShareed2kHoneyPkgPlace1(out, *v3)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Printable) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComShareed2kHoneyPkgPlace(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Printable) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComShareed2kHoneyPkgPlace(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Printable) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComShareed2kHoneyPkgPlace(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Printable) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComShareed2kHoneyPkgPlace(l, v)
}
func easyjson6601e8cdDecodeGithubComShareed2kHoneyPkgPlace1(in *jlexer.Lexer, out *Instance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = string(in.String())
		case "BackendName":
			out.BackendName = string(in.String())
		case "Name":
			out.Name = string(in.String())
		case "Type":
			out.Type = string(in.String())
		case "Status":
			out.Status = string(in.String())
		case "PrivateIP":
			out.PrivateIP = string(in.String())
		case "PublicIP":
			out.PublicIP = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComShareed2kHoneyPkgPlace1(out *jwriter.Writer, in Instance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"BackendName\":"
		out.RawString(prefix)
		out.String(string(in.BackendName))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"PrivateIP\":"
		out.RawString(prefix)
		out.String(string(in.PrivateIP))
	}
	{
		const prefix string = ",\"PublicIP\":"
		out.RawString(prefix)
		out.String(string(in.PublicIP))
	}
	out.RawByte('}')
}
